-
  name: "Configure MQTT for Assets"
  hosts: all
  gather_facts: no
  any_errors_fatal: true
  collections:
    - solace.pubsub_plus
  module_defaults:
    solace_gather_facts:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
      solace_cloud_api_token: "{{ solace_cloud_api_token | default(omit) }}"
      solace_cloud_service_id: "{{ solace_cloud_service_id | default(omit) }}"
    solace_client_profile:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
      msg_vpn: "{{ vpn }}"
      solace_cloud_api_token: "{{ solace_cloud_api_token | default(omit) }}"
      solace_cloud_service_id: "{{ solace_cloud_service_id | default(omit) }}"
    solace_acl_profile:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
      msg_vpn: "{{ vpn }}"
    solace_acl_publish_topic_exception:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
      msg_vpn: "{{ vpn }}"
    solace_acl_subscribe_topic_exception:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
      msg_vpn: "{{ vpn }}"
    solace_client_username:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
      msg_vpn: "{{ vpn }}"
    solace_mqtt_session:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
      msg_vpn: "{{ vpn }}"
      virtual_router: "{{ virtual_router }}"
    solace_mqtt_session_subscription:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
      msg_vpn: "{{ vpn }}"
      virtual_router: "{{ virtual_router }}"
  pre_tasks:
    - include_vars:
        file: "mqtt.vars.yml"
        name: mqtt
  tasks:

    - name: Get Solace Facts
      solace_gather_facts:

    - name: "MQTT: Client Profile"
      solace_client_profile:
        name: "{{ mqtt.name }}"
        settings:
          allowBridgeConnectionsEnabled: false
          allowGuaranteedMsgSendEnabled: true
          allowGuaranteedMsgReceiveEnabled: true
          allowGuaranteedEndpointCreateEnabled: true
          allowTransactedSessionsEnabled: false
        state: present

    - name: "MQTT: ACL Profile"
      solace_acl_profile:
        name: "{{ mqtt.name }}"
        settings:
          clientConnectDefaultAction: "allow"
          publishTopicDefaultAction: "disallow"
          subscribeTopicDefaultAction: "disallow"
        state: present

    - name: "MQTT: ACL Profile Publish Topic Exception"
      solace_acl_publish_topic_exception:
        semp_version: "{{ ansible_facts.solace.about.api.sempVersion }}"
        acl_profile_name: "{{ mqtt.name }}"
        name: "{{ pub_topic }}"
        state: present
      loop: "{{ mqtt.acl_profile.pub_topics }}"
      loop_control:
        loop_var: pub_topic

    - name: "MQTT: ACL Profile Subscribe Topic Exception"
      solace_acl_subscribe_topic_exception:
        semp_version: "{{ ansible_facts.solace.about.api.sempVersion }}"
        acl_profile_name: "{{ mqtt.name }}"
        name: "{{ sub_topic }}"
        state: present
      loop: "{{ mqtt.acl_profile.sub_topics }}"
      loop_control:
        loop_var: sub_topic

    - name: "MQTT: Client Usernames"
      solace_client_username:
        name: "{{ mqtt_asset.device_id }}"
        settings:
          enabled: false
          password: "{{ mqtt_asset.device_id }}"
          aclProfileName: "{{ mqtt.name }}"
          clientProfileName: "{{ mqtt.name }}"
        state: present
      loop: "{{ mqtt.mqtt_assets }}"
      loop_control:
        loop_var: mqtt_asset

    - name: "MQTT: Mqtt Sessions"
      include_tasks: ./tasks/mqtt-sessions.tasks.yml
      loop: "{{ mqtt.mqtt_assets }}"
      loop_control:
        loop_var: mqtt_asset

    - name: "MQTT: Client Usernames - Enable"
      solace_client_username:
        name: "{{ mqtt_asset.device_id }}"
        settings:
          enabled: true
        state: present
      loop: "{{ mqtt.mqtt_assets }}"
      loop_control:
        loop_var: mqtt_asset

    - name: "Get Facts: all client connection details"
      solace_get_facts:
        hostvars: "{{ hostvars }}"
        host: "{{ inventory_hostname }}"
        field_funcs:
          - get_allClientConnectionDetails
      register: result

    - set_fact:
        client_connection_details: "{{ result.facts }}"

    - name: "Save 'client_connection_details' to File"
      copy:
        content: "{{ client_connection_details | to_nice_json }}"
        dest: "{{ WORKING_DIR }}/edge-broker.client_connection_details.json"
