-
  name: Remove Services Playbook
  hosts: localhost
  gather_facts: no
  any_errors_fatal: true
  collections:
    - solace.pubsub_plus
  pre_tasks:
    - include_vars:
        file: "solace-cloud-service.vars.yml"
        name: sc_service
  tasks:

    - name: "Delete Solace Cloud Service"
      solace_cloud_service:
        api_token: "{{ SOLACE_CLOUD_API_TOKEN }}"
        name: "{{ sc_service.name }}"
        state: absent
      register: result

    - name: "Delete Solace Cloud Service Inventory"
      file:
        path: "{{ WORKING_DIR }}/edge-broker.inventory.yml"
        state: absent

    - name: "Delete Solace Cloud Certificate"
      file:
        path: "{{ WORKING_DIR }}/edge-broker.pem"
        state: absent

    - name: "Local Broker Remove"
      include_role:
        name: solace.pubsub_plus.solace_broker_service
      vars:
        project_name: central-broker
        state: absent

    - name: "Remove generated inventory"
      file:
        path: "{{ WORKING_DIR }}/central-broker.inventory.yml"
        state: absent
