-
    name: Configure - Get/Remove/Add/Update Queue objects with subscriptions
    hosts: all
    gather_facts: no
    any_errors_fatal: true
    collections:
      - solace.pubsub_plus
    module_defaults:
      solace_get_available:
        host: "{{ sempv2_host }}"
        port: "{{ sempv2_port }}"
        secure_connection: "{{ sempv2_is_secure_connection }}"
        username: "{{ sempv2_username }}"
        password: "{{ sempv2_password }}"
        timeout: "{{ sempv2_timeout }}"
        msg_vpn: "{{ vpn }}"
      solace_gather_facts:
        host: "{{ sempv2_host }}"
        port: "{{ sempv2_port }}"
        secure_connection: "{{ sempv2_is_secure_connection }}"
        username: "{{ sempv2_username }}"
        password: "{{ sempv2_password }}"
        timeout: "{{ sempv2_timeout }}"
        solace_cloud_api_token: "{{ solace_cloud_api_token | default(omit) }}"
        solace_cloud_service_id: "{{ solace_cloud_service_id | default(omit) }}"
      solace_acl_profile:
        host: "{{ sempv2_host }}"
        port: "{{ sempv2_port }}"
        secure_connection: "{{ sempv2_is_secure_connection }}"
        username: "{{ sempv2_username }}"
        password: "{{ sempv2_password }}"
        timeout: "{{ sempv2_timeout }}"
      solace_acl_publish_topic_exception:
        host: "{{ sempv2_host }}"
        port: "{{ sempv2_port }}"
        secure_connection: "{{ sempv2_is_secure_connection }}"
        username: "{{ sempv2_username }}"
        password: "{{ sempv2_password }}"
        timeout: "{{ sempv2_timeout }}"
      solace_acl_subscribe_topic_exception:
        host: "{{ sempv2_host }}"
        port: "{{ sempv2_port }}"
        secure_connection: "{{ sempv2_is_secure_connection }}"
        username: "{{ sempv2_username }}"
        password: "{{ sempv2_password }}"
        timeout: "{{ sempv2_timeout }}"
      solace_client_username:
        host: "{{ sempv2_host }}"
        port: "{{ sempv2_port }}"
        secure_connection: "{{ sempv2_is_secure_connection }}"
        username: "{{ sempv2_username }}"
        password: "{{ sempv2_password }}"
        timeout: "{{ sempv2_timeout }}"
    pre_tasks:
    - include_vars:
        file: "acl-users.vars.yml"
    tasks:
      - name: "Wait until broker service available"
        solace_get_available:
        register: available_result
      - fail:
          msg: "service not available"
        when: not available_result.is_available

      - name: Gather Solace Facts
        solace_gather_facts:

      - set_fact:
          semp_version: "{{ ansible_facts.solace.about.api.sempVersion }}"

      - name: Remove Client Usernames before removing the ACL Profile
        solace_client_username:
          name: "{{ item.name }}"
          msg_vpn: "{{ vpn }}"
          state: absent
        loop: "{{ users }}"

      - name: Remove ACL Profiles
        solace_acl_profile:
          name: "{{ item.name }}"
          msg_vpn: "{{ vpn }}"
          state: absent
        loop: "{{ acls }}"

      - name: Add ACL Profile
        solace_acl_profile:
          name: "{{ item.name }}"
          msg_vpn: "{{ vpn }}"
          settings:
            clientConnectDefaultAction: "{{ item.client_connect_default }}"
        loop: "{{ acls }} "

      - name: Remove ACL Publish Exception
        solace_acl_publish_topic_exception:
          name: "{{ item.1.topic }}"
          acl_profile_name: "{{ item.0.name }}"
          msg_vpn: "{{ vpn }}"
          state: absent
          semp_version: "{{ semp_version }}"
        with_subelements:
          - "{{ acls }}"
          - publish_topic_exceptions
          - flags:
            skip_missing: true

      - name: Add ACL Publish Exception
        solace_acl_publish_topic_exception:
          name: "{{ item.1.topic }}"
          acl_profile_name: "{{ item.0.name }}"
          msg_vpn: "{{ vpn }}"
          topic_syntax: "{{ item.1.syntax }}"
          semp_version: "{{ semp_version }}"
        with_subelements:
          - "{{ acls }} "
          - publish_topic_exceptions
          - flags:
            skip_missing: true

      - name: Remove ACL Subscribe Exception
        solace_acl_subscribe_topic_exception:
          name: "{{ item.1.topic }}"
          acl_profile_name: "{{ item.0.name }}"
          msg_vpn: "{{ vpn }}"
          state: absent
          semp_version: "{{ semp_version }}"
        with_subelements:
          - "{{ acls }} "
          - subscribe_topic_exceptions
          - flags:
            skip_missing: true

      - name: Add ACL Subscribe Exception
        solace_acl_subscribe_topic_exception:
          name: "{{ item.1.topic }}"
          acl_profile_name: "{{ item.0.name }}"
          msg_vpn: "{{ vpn }}"
          topic_syntax: "{{ item.1.syntax }}"
          semp_version: "{{ semp_version }}"
        with_subelements:
          - "{{ acls }} "
          - subscribe_topic_exceptions
          - flags:
            skip_missing: true

      - name: Add Clients
        solace_client_username:
          name: "{{ item.name }}"
          msg_vpn: "{{ vpn }}"
          settings:
            clientProfileName: "{{ item.client_profile }}"
            aclProfileName: "{{ item.acl_profile }}"
            password: "{{ item.password }}"
            enabled: "{{ item.enabled }}"
        loop: "{{ users }} "
