
---
    - name: "MQTT: Create Mqtt Session"
      solace_mqtt_session:
        name: "{{ mqtt_asset.device_id }}"
        settings:
          enabled: true
          owner: "{{ mqtt_asset.device_id }}"
        state: present

    # enable if mqtt client implements a generic callback for any subscription
    - name: "MQTT: Subscriptions"
      solace_mqtt_session_subscription:
        client_id: "{{ mqtt_asset.device_id }}"
        topic: "{{ mqtt_asset.subscr_topic }}"
        settings:
          subscriptionQos: 1
        state: present
