
---
  - name: "Queue: Disable Egress"
    # required to update the owner
    solace_queue:
      name: "{{ item.name }}"
      settings:
        egressEnabled: false
      state: present

  - name: "Queue: Create/Update"
    solace_queue:
      name: "{{ item.name }}"
      settings:
        egressEnabled: true
        ingressEnabled: true
        permission: "consume"
        owner: "{{ rdp.name }}"
      state: present

  - name: "Queue: Enable Egress"
    solace_queue:
      name: "{{ item.name }}"
      settings:
        egressEnabled: true
      state: present

###
# The End.
