# Tasks to add/update a queue
# include & use to loop over tasks
---
    - name: Create Queue
      solace_queue:
        name: "{{ queue_item.name }}"
        msg_vpn: "{{ vpn_name }}"
        settings:
          egressEnabled: false
          ingressEnabled: false
        state: present

    - name: Update queue
      solace_queue:
        name: "{{ queue_item.name }}"
        msg_vpn: "{{ vpn_name }}"
        settings:
          permission: "consume"
          accessType: non-exclusive          
        state: present

    - name: Add / Update all subscriptions
      solace_queue_subscription:
        queue: "{{ queue_item.name }}"
        name: "{{ item }}"
        msg_vpn: "{{ vpn_name }}"
        state: present
      loop: "{{ queue_item.subscriptions }}"

    - name: Enable Egress of Queue
      solace_queue:
        name: "{{ queue_item.name }}"
        msg_vpn: "{{ vpn_name }}"
        settings:
          egressEnabled: true
          ingressEnabled: true
        state: present
