-
  name: Solace Cloud Facts
  hosts: all
  gather_facts: no
  any_errors_fatal: true
  collections:
    - solace.pubsub_plus
  module_defaults:
    solace_gather_facts:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
      solace_cloud_service_id: "{{ solace_cloud_service_id | default(omit) }}"

  tasks:

    - name: "Check vars"
      assert:
        that:
          - WORKING_DIR is defined
          - SOLACE_CLOUD_API_TOKEN is defined and SOLACE_CLOUD_API_TOKEN | length > 0
        fail_msg: "one or more variables not defined"

    - name: "Gather Solace Facts"
      solace_gather_facts:
        solace_cloud_api_token: "{{ SOLACE_CLOUD_API_TOKEN }}"
      register: result
      no_log: true

    - name: "Get Facts: all client connection details"
      solace_get_facts:
        hostvars: "{{ hostvars }}"
        host: "{{ inventory_hostname }}"
        field_funcs:
          - get_allClientConnectionDetails
      register: result
      no_log: true

    - set_fact:
        client_connection_details: "{{ result.facts }}"
      no_log: true

    - name: "Save 'client_connection_details' to File"
      copy:
        content: "{{ client_connection_details | to_nice_yaml }}"
        dest: "{{ WORKING_DIR }}/solace-cloud.{{ inventory_hostname }}.client_connection_details.yml"
      changed_when: false
