-
  name: Configure Playbook
  hosts: all
  gather_facts: no
  any_errors_fatal: true
  collections:
    - solace.pubsub_plus
  module_defaults:
    solace_queue:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
      msg_vpn: "{{ vpn }}"
    solace_queue_subscription:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
      msg_vpn: "{{ vpn }}"
  tasks:

    - name: create queue
      solace_queue:
        name: quickstart_queue

    - name: add subscription
      solace_queue_subscription:
        queue: quickstart_queue
        name: "quickstart/topic"

    # create user message
    - set_fact:
        broker_url: "{{ 'https' if sempv2_is_secure_connection else 'http' }}://{{ sempv2_host }}:{{ sempv2_port }}"
    - name: message
      debug:
        msg:
          - "open private browser window: {{ broker_url }}"
          - "login: {{ sempv2_username }} / {{ sempv2_password }}"
          - "vpn: default"
          - "Queues: quickstart_queue"
          - "Subscriptions: quickstart/topic"
