-
  name: "quickstart teardown"
  hosts: localhost
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - stat: path="{{ WORKING_DIR }}/broker.inventory.yml"
      register: r
    - assert:
        that: r.stat.exists == True

    - name: "Local Broker Remove"
      include_role:
        name: solace.pubsub_plus.solace_broker_service
      vars:
        project_name: broker_service_single_node
        state: absent

    - name: "Remove generated inventory"
      file:
        path: "{{ WORKING_DIR }}/broker.inventory.yml"
        state: absent
